meta_title: "Classic"
meta_description: "CLASSIC Paris est un label de création couvrant les activités d’édition, de curating et de consulting. Depuis 2010, nos différents projets nous ont permis de faire le pont entre des univers aussi variés que l’art, le design, la mode ou la musique."
meta_image: "logo_classic.png"
