# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5e5d314ab334209aed834346a2a75becf80be952267ba80c9792f560256e3dc4d23a897a15f9b0fd3db1a5233bbdd90349f1eca3d6aa80bee21c57587b1922d
  HOST: http://localhost:3000/

test:
  secret_key_base: b167e1ecd6ecd5f9da21187b9248d4e1b88b4224a9e796c3eac1418132c55a42cfe4bab4a733b8c0dc3698489bbbda5b613c857ad9a946371cc1c14d758bcf7f
  HOST: http://localhost:3000/

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  HOST: http://www.classic-paris.com/
